# Generated by Django 5.1.5 on 2025-02-01 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="field",
            name="farm_size",
        ),
        migrations.AlterField(
            model_name="field",
            name="crop_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Current crop planted in this field",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="monitoring.croptype",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="size",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Size in hectares",
                max_digits=10,
                null=True,
            ),
        ),
    ]
