# Generated by Django 5.1.5 on 2025-02-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0002_remove_field_farm_size_alter_field_crop_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="is_forecast",
            field=models.BooleanField(default=False),
        ),
    ]
